name: "I have issues"
description: "Consume the output of the previous action and create a new issue"

inputs:
  joke:
    description: "This will become the body of created issue"
    required: true
  issue-title:
    description: "Every issue needs a title!"
    default: "a joke for you!"
    required: true
  repo-token:
    description: "Thoken with permissions"
    required: true

runs:
  using: "node12"
  main: "index.js"      
